name: Process Issue to Create Branch and PR

on:
  issues:
    types: 
      - opened  # Trigger when an issue is opened
      - reopened
permissions:
  contents: write
  pull-requests: write

jobs:
  label_check:
    runs-on: ubuntu-latest
    permissions:
      issues: write 
    outputs:
      label_found: ${{ steps.check_label.outputs.label_found }}

    steps:
      - name: Check if "admin request" label is present
        id: check_label
        run: |
          echo "Labels: ${{ toJson(github.event.issue.labels) }}"
    
          if [[ "${{ contains(github.event.issue.labels.*.name, 'admin request') }}" == "true" ]]; then
            echo "Label 'admin request' found. Proceeding..."
            echo "label_found=true" >> $GITHUB_ENV
            echo "label_found=true" >> $GITHUB_OUTPUT
          else
            echo "Label 'admin request' not found. Exiting..."
            echo "label_found=false" >> $GITHUB_ENV
            echo "label_found=false" >> $GITHUB_OUTPUT
          fi

  handle-issue:
    needs: label_check
    if: needs.label_check.outputs.label_found == 'true'  # Run only if label admin_request is found
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: pip install ruamel.yaml 

    - name: Extract data from issue
      id: extract_course_info
      run: |
        echo "Extracting course information ..."
        python3 .github/scripts/admin_request/extract_course_info.py

    - name: Print extracted information
      run: |
        echo "COURSE_ID: ${{ steps.extract_course_info.outputs.course_id }}"
        echo "HUB_NAME: ${{ steps.extract_course_info.outputs.hub_name }}"
        echo "NEW_BRANCH: ${{ steps.extract_course_info.outputs.new_branch }}"

    - name: Create new branch and modify config
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git checkout -b "${{ steps.extract_course_info.outputs.new_branch }}"

        python3 .github/scripts/admin_request/add_admin_config.py 
  
        git add deployments/${{ steps.extract_course_info.outputs.hub_name }}/config/common.yaml
        git commit -m "Add config for ${COURSE_ID}"
        git push origin "${{ steps.extract_course_info.outputs.new_branch }}"

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        source: ${{ steps.extract_course_info.outputs.new_branch }}
        base: staging
        title: "Add ${{ steps.extract_course_info.outputs.course_id }} config (issue #${{ github.event.issue.number }})"
        body: |
          Automatically generated PR to add admin configs for `${{ steps.extract_course_info.outputs.course_id }}`