name: Issue Created and Label Found

on:
  issues:
    types: [opened]  # Trigger when an issue is opened
  

jobs:
  label_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check if "data retrieval" label is present
        id: check_label
        run: |
          echo "Labels: ${{ toJson(github.event.issue.labels) }}"
    
          if [[ "${{ contains(github.event.issue.labels.*.name, 'data retrieval') }}" == "true" ]]; then
            echo "Label 'data retrieval' found. Proceeding..."
            echo "label_found=true" >> $GITHUB_ENV
          else
            echo "Label 'data retrieval' not found. Exiting..."
            echo "label_found=false" >> $GITHUB_ENV
            exit 1
          fi

      - name: Extract the "Link to Your Folder" from issue body
        id: extract_link
        uses: actions/github-script@v6
        with:
          script: |
            const issueBody = `${{ github.event.issue.body }}`;

            // Define patterns for the link and email
            const linkPattern = /(gs:\/\/[^\s]+\.tar\.gz)/;
            const emailPattern = /###\s*Your UC Berkeley Email Address\s*([\w._%+-]+@berkeley\.edu)/;

            // Extract folder link
            const linkMatch = issueBody.match(linkPattern);
            if (linkMatch && linkMatch[1]) {
              const folderLink = linkMatch[1];
              console.log(`Found link: ${folderLink}`);
              core.setOutput("folderlink", folderLink);  // Set the folder link as output
            } else {
              throw new Error('Link not found in issue body');
            }

            // Extract email
            const emailMatch = issueBody.match(emailPattern);
            if (emailMatch && emailMatch[1]) {
              const email = emailMatch[1];
              console.log(`Found email: ${email}`);
              core.setOutput("email", email);  // Set the email as output
            } else {
              throw new Error('Email not found in issue body');
            }


      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Check whether email matches the folder name
        env:
          EXTRACTED_LINK: ${{ steps.extract_link.outputs.folderlink }}
          RECEIVER_EMAIL: ${{ steps.extract_link.outputs.email }}
        run: |
          python3 .github/scripts/username_mapping.py
      
      - name: Check if environment variable is "invalid"
        id: check_env_var
        run: |
          if [ "${{ env.emailMatchesFolder }}" == "invalid" ]; then
            echo "The provided email does not match the folder name requested. Please double check your email and the path to the requested resource."
            
            # Post a comment on the issue
            COMMENT_BODY='The provided email does not match the folder name requested. Please double check your email and the path to the requested resource.'
            ISSUE_NUMBER=${{ github.event.issue.number }}
            curl -X POST \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Content-Type: application/json" \
              -d "{\"body\": \"$COMMENT_BODY\"}" \
              "https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER/comments"
              
            # Close the issue
            curl -X PATCH \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Content-Type: application/json" \
              -d '{"state": "closed"}' \
              "https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER"
              
            exit 1
          else
            echo "Environment variable is valid, continuing."
          fi

      - name: Install Google Cloud SDK and Python Client Libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install --upgrade google-cloud-storage google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

      - name: Sign URL
        env:
          EXTRACTED_LINK: ${{ steps.extract_link.outputs.folderlink }}
          GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.DATA_RETRIEVAL_SA }}
        if: steps.check_env_var.outcome == 'success'
        run: |
          python3 .github/scripts/sign_url.py

      - name: Run the Python script to send email
        id: run_send_email_python_script
        run: |
          python3 .github/scripts/send_email_oauth.py
        env:
          TOKEN_PICKLE: ${{ secrets.TOKEN_PICKLE }}
          SIGNEDURL: ${{ env.signedURL}}
          RECEIVER_EMAIL: ${{ steps.extract_link.outputs.email }}
      
      - name: Post success comment and close the issue
        if: steps.run_send_email_python_script.outcome == 'success'
        run: |
          # Post a success comment on the issue
          COMMENT_BODY='The requested resource has been sent to your provided email address. You have 7 days from when the email was received to retrieve your data.'
          ISSUE_NUMBER=${{ github.event.issue.number }}
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{\"body\": \"$COMMENT_BODY\"}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER/comments"
          
          # Close the issue
          curl -X PATCH \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"state": "closed"}' \
            "https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER"

          
