name: Dispatcher Workflow

on:
  issues:
    types: [opened, reopened]

permissions:
  contents: read
  actions: write  
  issues: read

jobs:
  dispatch-data-retrieval:
    if: contains(toJson(github.event.issue.labels), 'data retrieval')
    uses: ./data-retrieval.yaml
    with:
      issue_number: ${{ github.event.issue.number }}

  dispatch-add-admin-config:
    if: contains(toJson(github.event.issue.labels), 'add admin config')
    uses: ./add_admin_config.yaml
    with:
      issue_number: ${{ github.event.issue.number }}

  dispatch-remove-admin-config:
    if: contains(toJson(github.event.issue.labels), 'remove admin config')
    uses: ./remove_admin_config.yaml
    with:
      issue_number: ${{ github.event.issue.number }}

  dispatch-add-memory-config:
    if: contains(toJson(github.event.issue.labels), 'add memory config')
    uses: ./add_memory_config.yaml
    with:
      issue_number: ${{ github.event.issue.number }}

  dispatch-remove-memory-config:
    if: contains(toJson(github.event.issue.labels), 'remove memory config')
    uses: ./remove_memory_config.yaml
    with:
      issue_number: ${{ github.event.issue.number }}
