name: Remove Shared directory Configs at the End of the Course and Create a PR

on:
  workflow_call:
    inputs:
      issue_number:
        required: true
        type: number

permissions:
  contents: write
  pull-requests: write

jobs:
  label_check:
    runs-on: ubuntu-latest
    permissions:
      issues: write 
    outputs:
      label_found: ${{ steps.check_label.outputs.label_found }}

    steps:
      - name: Check if "remove shared directories" label is present
        id: check_label
        run: |
          echo "Labels: ${{ toJson(github.event.issue.labels) }}"
    
          if [[ "${{ contains(github.event.issue.labels.*.name, 'remove shared directories') }}" == "true" ]]; then
            echo "Label 'remove shared directories' found. Proceeding..."
            echo "label_found=true" >> $GITHUB_ENV
            echo "label_found=true" >> $GITHUB_OUTPUT
          else
            echo "Label 'remove shared directories' not found. Exiting..."
            echo "label_found=false" >> $GITHUB_ENV
            echo "label_found=false" >> $GITHUB_OUTPUT
          fi

  handle-issue:
    needs: label_check
    if: needs.label_check.outputs.label_found == 'true'  # Run only if label admin_request is found
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Write issue body to file
      run: echo "${{ github.event.issue.body }}" > issue_body.txt

    - name: Extract data from issue
      id: extract_course_info
      run: |
        python3 .github/scripts/extract_course_info.py  issue_body.txt
      env:
        ISSUE_NUMBER: ${{ github.event.issue.number }}

    - name: Create new branch and modify config
      id: modify-config
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git checkout -b "${{ steps.extract_course_info.outputs.new_branch }}"

        python3 .github/scripts/shared_directories/remove_shared_directories.py 
        FILE_PATH="deployments/${{ steps.extract_course_info.outputs.hub_name }}/config/common.yaml"

        if ! git diff --quiet "$FILE_PATH"; then
          echo "Changes detected in $FILE_PATH. Committing..."
          git add "$FILE_PATH"
          git commit -m "Remove shared directories config for ${{ steps.extract_course_info.outputs.course_id }} to $FILE_PATH"
          git push origin "${{ steps.extract_course_info.outputs.new_branch }}"
          echo "changed=true" >> "$GITHUB_OUTPUT"
        else
          echo "No changes detected in $FILE_PATH. Skipping commit and push."
          echo "changed=false" >> "$GITHUB_OUTPUT"
        fi
      env:
        hub_name: ${{ steps.extract_course_info.outputs.hub_name }}
        course_id: ${{ steps.extract_course_info.outputs.course_id }}
    
    - name: Authenticate gh CLI
      if: steps.modify-config.outputs.changed == 'true'
      run: echo "${{ secrets.MYPAT }}" | gh auth login --with-token

    - name: Create Pull Request
      if: steps.modify-config.outputs.changed == 'true'
      env:
        BRANCH_NAME: ${{ steps.extract_course_info.outputs.new_branch }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
      run: |
        # Set reviewers (GitHub usernames)
        REVIEWERS="yijunge-ucb"
        LABELS="remove shared directories,support"

        # Check if PR already exists
        if gh pr list --base main --head "$BRANCH_NAME" --json number | grep -q '"number":'; then
          echo "PR already exists. Skipping."
        else
          gh pr create \
            --base main \
            --head "$BRANCH_NAME" \
            --title "Automatic PR created: merge from $BRANCH_NAME to main" \
            --body "Automatic PR created: merge from $BRANCH_NAME to main" \
            --reviewer "$REVIEWERS" \
            --label "$LABELS"
        fi